shell: main.o functions.o command_calc.o command_get.o command_path.o command_put.o command_sys.o command_time.o
	gcc -g -o shell main.o functions.o command_calc.o command_get.o command_path.o command_put.o command_sys.o command_time.o

main.o: main.c
	gcc -g -c main.c

functions.o: functions.c
	gcc -g -c functions.c

command_calc.o: command_calc.c
	gcc -g -c command_calc.c

command_get.o: command_get.c
	gcc -g -c command_get.c

command_path.o: command_path.c
	gcc -g -c command_path.c

command_put.o: command_put.c
	gcc -g -c command_put.c

command_sys.o: command_sys.c
	gcc -g -c command_sys.c

command_time.o: command_time.c
	gcc -g -c command_time.c



